### ISSUE TITLE
Request: Make generated QR code cached by default and only save when selecting "Save QR code"

### ISSUE THREAD

**Issue by R-Bose** [asmpro7/QrFlow#2]
Hey!!
I really like the plugin, quick and easy to generate QR codes for multiple purposes.

In order to prevent cluttering of QR codes that are generated for temporary purposes, maybe it would be better to change the default behaviour to cache the generated image and then prompt the user to save it as the 3rd option (Save File and Open Location).

**Comment by asmpro7** [comment]
Im happy for my plugin help you, 
and I will work on your request this weekend 🤝
